### ISSUE TITLE
Retired?

### ISSUE THREAD

**Issue by lakesol** [skttl/umbraco-blocklistmvc#1]
Hi there,

I found this package here: https://our.umbraco.com/packages/developer-tools/block-list-mvc/

It says that its now retired.  I am looking for a solution which does this in v9, do you know if there is a newer approach to do the same operation in v9?

Thanks
Lake

**Comment by skttl** [comment]
Yes, it is retired.

Check out https://github.com/Adolfi/UmbracoNineDemoSite it has something similar.
